
project_id = "iqxvtfupjjxjkbajgcve"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MB"

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[functions.calendly-webhook]
verify_jwt = false

[functions.calendly-sync-gaps]
verify_jwt = true

[functions.calendly-oauth]
verify_jwt = true

[functions.calendly-oauth-callback]
verify_jwt = false

[functions.ghl-webhook]
verify_jwt = false

[functions.integration-oauth]
verify_jwt = true

[functions.integration-oauth-callback]
verify_jwt = false

[functions.integration-sync]
verify_jwt = true

[functions.track-event]
verify_jwt = false

[functions.secure-track-event]
verify_jwt = false

[functions.zoho-oauth]
verify_jwt = false

[functions.unified-integration-scheduler]
verify_jwt = false

[edge-runtime]
policy = "per_request"
